演習課題（UIトレース）
shinonome-inc/qiita_client_yusei pull request #1
Opened 2023-02-19 09:23 UTC by iu-yusei

レビューをお願いします。

2023-02-19 11:08 UTC, KobayashiYoh requested changes
コメントしました。

2023-02-19 11:08 UTC, KobayashiYoh commented on lib/main.dart
> +            ),
UIの細部まで再現できていて良いですね👍

2023-02-19 11:08 UTC, KobayashiYoh commented on lib/main.dart
> +                height: 50,
現状だと、iPhone SEのような縦幅が比較的狭い端末でビルドするとレイアウトが崩れしまいます。
どの端末でビルドしてもレイアウトが崩れないアプリを目指しましょう。
<img src="https://user-images.githubusercontent.com/82624334/219944081-d679b0e8-a8d1-4ab1-a895-6e61485fb19c.png" width="300">

2023-02-19 11:41 UTC, iu-yusei commented on lib/main.dart
> +                height: 50,
レビューいただきありがとうございます。
様々な端末サイズに適応できるようにコードを修正したいと思います。

2023-02-20 03:15 UTC, iu-yusei commented
@KobayashiYoh 
ご指摘いただいた点を修正いたしました。
再度レビューをいただけますと幸いです。

2023-02-20 05:19 UTC, KobayashiYoh commented
> @KobayashiYoh ご指摘いただいた点を修正いたしました。 再度レビューをいただけますと幸いです。

しっかり修正できています👍

2023-02-20 05:37 UTC, KobayashiYoh commented
書いていただいたコード自体はOKです🙆
ただ、現状だと`.gitignore`が削除されており、gitの差分が大量に発生してしまっているため、`.gitignore`ファイルをプロジェクトに追加していただきたいです。
手順は以下の通りです。
### 1. プロジェクト直下に`.gitignore`ファイルを作成
プロジェクト直下（ファイルのパスがqiita_client_yusei/.gitignoreとなるよう）に`.gitignore`を作成してください

### 2. プロジェクト直下に`.gitignore`にgitの管理下から外したい項目を追加
作成した`.gitignore`に以下を追加してください。
```
# Miscellaneous
*.class
*.log
*.pyc
*.swp
.DS_Store
.atom/
.buildlog/
.history
.svn/
migrate_working_dir/

# IntelliJ related
*.iml
*.ipr
*.iws
.idea/

# The .vscode folder contains launch configuration and tasks you configure in
# VS Code which you may wish to be included in version control, so this line
# is commented out by default.
#.vscode/

# Flutter/Dart/Pub related
**/doc/api/
**/ios/Flutter/.last_build_id
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub-cache/
.pub/
/build/

# Symbolication related
app.*.symbols

# Obfuscation related
app.*.map.json

# Android Studio will place build artifacts here
/android/app/debug
/android/app/profile
/android/app/release
```

### 3. 一部のファイルをgitの管理下から外すためにコマンドを実行
```git rm --cached -r .dart_tool```
```git rm --cached -r .idea```
```git rm --cached -r build```

### 4. add&commit&push
変更を反映させる

ここまでできれば以下のような表示になると思います。
<img width="967" alt="スクリーンショット 2023-02-20 14 36 25" src="https://user-images.githubusercontent.com/82624334/220017689-5f6076b1-6807-474e-9f2b-faa27aefcaee.png">

2023-02-20 05:37 UTC, KobayashiYoh approved these changes

2023-02-22 15:42 UTC, Yoshida-koshi reviewed
コメントしました〜

2023-02-22 15:42 UTC, Yoshida-koshi commented on lib/main.dart
> +            ),
「ログインせずに利用する」のところもボタンにしてほしいです！

2023-02-22 15:42 UTC, Yoshida-koshi commented on lib/main.dart
> +      deviceHeight = size.height;
28, 29行目も同じような記述があるので、まとめてあげるといいと思います！

2023-02-22 15:42 UTC, Yoshida-koshi commented on lib/main.dart
> +    } else if (aspectRatio < 0.65) {
この0.65はなんでこの値にしたのですか？？

2023-02-22 15:42 UTC, Yoshida-koshi commented on lib/main.dart
> +                height: 2.5,
heightを指定した理由はなんですか？

2023-02-23 07:33 UTC, na7ei commented on lib/main.dart
> +            ),
了解です！

2023-02-23 07:33 UTC, iu-yusei commented on lib/main.dart
> +      deviceHeight = size.height;
ご助言ありがとうございます！

2023-02-23 08:01 UTC, iu-yusei commented on lib/main.dart
> +                height: 2.5,
-PlayGround-という文字の上部に余白を確保したかったので、heightを指定しました。

※ line height(20px)と上部の余白分(8px)を合わせて、28px確保したかったので、次コミットでheightの値を2.0に変更しました。

2023-02-23 08:26 UTC, iu-yusei commented on lib/main.dart
> +    } else if (aspectRatio < 0.65) {
0.65という値は、[https://qiita.com/1hour/items/c2e1d1c8eaf78a8d615c#:~:text=%E9%83%A8%E5%88%86%E3%81%A7%E3%81%99%E3%81%AD%E3%80%82-,%E5%85%A8%E4%BD%93%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AF%E4%BB%A5%E4%B8%8B%E3%81%AE%E9%80%9A%E3%82%8A%E3%81%A7%E3%81%99%E3%80%82,-import%20%27package%3Aflutter](こちらの記事)を参考にして設定しました。

コピペで持ってきたものなので、特に条件分岐の境目を深く考えて、値を設定したわけではありません。

2023-02-23 09:04 UTC, iu-yusei commented on lib/main.dart
> +    } else if (aspectRatio < 0.65) {
以下の記事を参考にして、条件を少し書き換えました。

[スマホのアスペクト比の統計](http://lovee7.blog.fc2.com/blog-entry-146.html)
[Apple製品のアスペクト比](https://uzurea.net/iphone-ipad-resolutions/)


【新たに設定した条件】
- 多くのスマホ（アスペクト比0.56以上0.65未満）
- 古い世代、タブレット（アスペクト比 0.65以上）
- 新世代スマホ（アスペクト比0.56未満）


**=====　↓多くのスマホ　=====**

シェア率1位
aspectRatio = 0.56221889055

iPhone5
aspectRatio = 0.56338028169

iPhone5c ~ 8 plus、iPhoneSE類
aspectRatio = 0.56

**=====　↓古い世代、タブレット　======**

iPhone ~ iPhone4s
aspectRatio = 0.66666666666

iPad mini　第６世代
aspectRatio = 0.65666372462

iPad Pro
aspectRatio = 0.69849246231

iPad, iPad mini, iPad Air, iPad Pro
aspectRatio = 0.75

**=======　↓新世代スマホ　========**

iPhoneX以降　SEを除く
aspectRatio = 0.47368421052

2023-02-23 09:10 UTC, iu-yusei commented
@Yoshida-koshi @KobayashiYoh 
修正＆少し変更を加えました！
再レビューをお願いいたします！

2023-02-23 09:32 UTC, Yoshida-koshi commented on lib/main.dart
> +            ),
OKです！

2023-02-23 09:39 UTC, Yoshida-koshi commented on lib/main.dart
> +    } else if (aspectRatio < 0.65) {
様々なスマホを想定して考えられてますね！素晴らしいです！
コードの方もOKです！

2023-02-23 09:39 UTC, Yoshida-koshi commented on lib/main.dart
> +      deviceHeight = size.height;
変えた条件の方はOKです！

2023-02-23 09:52 UTC, Yoshida-koshi commented on lib/main.dart
> +                height: 2.5,
今回はQiita Feed Appと-PlayGround-はどちらも半角英数字なので、Qiita Feed Appと-PlayGround-の間にSizedBoxで余白を取ってあげた方が簡単だと思ったのですが、いかがでしょうか？

2023-02-23 10:07 UTC, iu-yusei commented on lib/main.dart
> +                height: 2.5,
コメントありがとうございます！
確かにSizedBoxで直接28pxと指定した方が楽だと思います！

高さを調整する方法としては下記3つがあると思うのですが、、、

- Paddingで余白を追加して高さを調整する方法
- SizedBoxで高さを調整する方法
- heightで高さを調整する方法

今回はあえてheightのみで調整できるか試してみました！

ご提案いただいたSizedBoxを用いたバージョンも試してみます！

2023-02-23 10:12 UTC, iu-yusei commented on lib/main.dart
> +            ),
🙇

2023-02-23 10:13 UTC, iu-yusei commented on lib/main.dart
> +      deviceHeight = size.height;
🙇

2023-02-23 10:13 UTC, iu-yusei commented on lib/main.dart
> +    } else if (aspectRatio < 0.65) {
🙇

2023-02-23 10:32 UTC, na7ei commented on lib/main.dart
> +                height: 2.5,
[20baeea](https://github.com/shinonome-inc/qiita_client_yusei/pull/1/commits/20baeea72310ebb04002b298e468111349da041f)

SizedBoxを用いたバージョンで書き直してみました！

2023-02-25 13:58 UTC, merged