5 create tag screen
shinonome-inc/qiita_client_yusei pull request #10
Opened 2023-03-16 18:20 UTC by iu-yusei

**Tag画面の実装**を行いました。
レビューいただけますと幸いです。

## ①実装内容（全体）

※以下のチェックボックスにチェックがついているものは、iOS・Androidともに動作確認ができた機能です。

- [x] **タグに紐づいたデータ表示→完了**

<br>

- [x] **タグをタップして遷移→完了**
<br>

- [x] **ページネーション実装→完了**

> ↓プレビュー画面（iPhone 14）
> <img src="https://user-images.githubusercontent.com/78660150/225706378-69a1b68d-f355-4a0f-abcf-9b2b9a5e704f.gif" width="280px">

<br>

> ↓プレビュー画面（iPad Air）
> <img src="https://user-images.githubusercontent.com/78660150/225706919-96b69dfa-7fd4-4551-b97a-43f51f8418c3.gif" width="380px">

<br>

## ②実装内容（詳細）

### **lib/api/qiita_api_service.dart**
 - タグデータを取得するためのメソッド（`fetchTagList`）を追記

<br>

### **lib/screens/tag_detail_list_page.dart**
- 遷移先として、設定したページ（タップされたタグのタイトルを取得し、AppBarに表示）

<br>

### **lib/screens/tag_page.dart**
- タグ一覧をGridViewで表示するWidgetを追記
※インターネット未接続の場合はNoInternetWidgetを表示する。

> ↓プレビュー画面（Android）
> <video src="https://user-images.githubusercontent.com/78660150/225715287-e5d71eb4-1979-4273-9efc-62c00a80b11b.webm"></video>

<br>

### **lib/view_model/tag_view_model.dart**
- tag_page.dartの状態を管理するためのクラスや、メソッドを定義。

<br>

2023-03-20 05:37 UTC, KobayashiYoh requested changes
コメントしました。
差分が多い割にコードの完成度が高くて驚きました。

2023-03-20 05:37 UTC, KobayashiYoh commented on lib/api/qiita_api_service.dart
> +          itemsCount: tagData['items_count'] ?? 0,
nullの処理までしっかりとされている点が非常にポイント高いですね👍

2023-03-20 05:37 UTC, KobayashiYoh commented on lib/screens/tag_page.dart
> +          : null,
`connectionStatus.interNetConnected`がtrueの場合もfalseの場合もnullになるのならば、appBarは常にnullなので省略してもいいかもしれませんね。
修正するかしないかはお任せします。

2023-03-20 05:37 UTC, KobayashiYoh commented on lib/screens/tag_page.dart
> +                                reverse: true,
上から下へスクロールしていくように実装お願いします🙏
コース修了生のTag Pageのプルリクを見てみるとイメージが湧きやすいかなと思います。

2023-03-20 05:37 UTC, KobayashiYoh commented on lib/view_model/tag_view_model.dart
単なるモデルのTagクラスと状態管理などのロジックを記述したTagViewModelクラスはクラスとしての役割が異なるため、ディレクトリやファイルを分けた方がいいかもしれませんね。
修正は任意です。

2023-03-20 07:20 UTC, iu-yusei commented on lib/api/qiita_api_service.dart
> +          itemsCount: tagData['items_count'] ?? 0,
🙇‍♂️

2023-03-20 07:20 UTC, iu-yusei commented on lib/screens/tag_page.dart
> +          : null,
アドバイスありがとうございます。
AppBarは削除します。

2023-03-20 07:20 UTC, iu-yusei commented on lib/screens/tag_page.dart
> +                                reverse: true,
了解です！
修正します！

2023-03-20 08:24 UTC, iu-yusei commented on lib/view_model/tag_view_model.dart
アドバイスありがとうございます。
`model/tag.dart`ファイルに切り分けました！

2023-03-20 08:25 UTC, iu-yusei commented
@KobayashiYoh 

ご指摘いただいた点を修正し、コミットしました！
再レビューいただけますと幸いです！

## 追加実装の内容

### ① `tag_page.dart`のappBarを削除

https://github.com/shinonome-inc/qiita_client_yusei/pull/10#discussion_r1141333832


### ②tagページのスクロール方向を上から下に変更

GridViewのreverseプロパティをデフォルトのfalseに変更しました。

https://github.com/shinonome-inc/qiita_client_yusei/pull/10#discussion_r1141335408


### ③Tagクラスを`model/tag.dart`ファイルに切り分け

Before→`view_model/tag_view_model.dart`ファイル
After→`model/tag.dart`ファイル

https://github.com/shinonome-inc/qiita_client_yusei/pull/10#discussion_r1141640810



## プレビュー画面(iOS)

<img src="https://user-images.githubusercontent.com/78660150/226271624-1de60e14-ad14-40af-a9bc-b6b05c5462e3.gif" width="320">


## プレビュー画面(Android)
<video src="https://user-images.githubusercontent.com/78660150/226271744-b0614fbd-b44c-4d18-9177-97f2da32808d.webm"></video>

2023-03-20 09:01 UTC, KobayashiYoh approved these changes

2023-03-20 09:01 UTC, KobayashiYoh commented
LGTMです👍
二次レビューに進んでください！

2023-03-22 13:03 UTC, mcz9mm requested changes

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +    Future.delayed(Duration.zero, () {
もしかして`fetchTags `でawaitさせるために遅延使ってる？
のであれば↓みたいに書けます
```
Future(() async {
   await tagViewModel.fetchTags();
 });
```

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +class TagCard extends StatelessWidget {
基本は1クラス1ファイルで書いてほしいです。
`tag_card.dart`ファイルを作成してそちらに移動させてください。

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +                  if (isConnected) {
if文で値をセットするなら直接入れちゃおう
```
setState(() {
    connectionStatus.interNetConnected = isConnected;
});
if (isConnected) {
  model.fetchTags();
}
```

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +                        if (Theme.of(context).platform ==
これAndroidだけ指定してるのって何か理由あったりしますか？

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +                                    return SizedBox(
widthもheightも指定しないのであれば`SizedBox `である必要はないかなと

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +                      height: 12 / 12,
1で良いかな

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +                      height: 12 / 12,
1で良いかな

2023-03-22 13:03 UTC, mcz9mm commented on lib/screens/tag_page.dart
> +            if (model.isLoading && model.tags.isEmpty) {
結局returnで返してるの同じWidgetなので条件を工夫して１個だけ返せるようにするか、
Widgetを関数化してあげるようにしてください。
DRYの原則って調べてみて。
```
            if (model.isLoading && model.tags.isEmpty) {
              return const Center(
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: CircularProgressIndicator(),
                ),
              );
            } else if (model.tags.isNotEmpty && model.tags.last == tag) {
              if (model.isLoading) {
                return const Center(
                  child: Padding(
                    padding: EdgeInsets.all(16),
                    child: CircularProgressIndicator(),
                  ),
                );
              } else if (!model.isLastPage) {
                return const Center(
                  child: Padding(
                    padding: EdgeInsets.all(16),
                    child: CircularProgressIndicator(),
                  ),
                );
              }
            }
```

2023-03-22 13:08 UTC, ShuheiYoshidaJP reviewed
コメントしました。

2023-03-22 13:08 UTC, ShuheiYoshidaJP commented on lib/view_model/tag_view_model.dart
> +  final ScrollController _scrollController = ScrollController();
使ってなさそうですね。

2023-03-22 13:08 UTC, ShuheiYoshidaJP commented on lib/screens/tag_page.dart
> +                    });
setStateはStateクラスないで定義された状態を更新するメソッドだと思います。connectionStatusは_TagPageStateの状態には属さない感じですよね？？

2023-03-23 02:20 UTC, iu-yusei commented on lib/screens/tag_page.dart
> +                        if (Theme.of(context).platform ==
Androidのみ、この条件式でないと、fetchTagsが発火してくれないので、指定しました！

2023-03-23 03:17 UTC, iu-yusei commented on lib/screens/tag_page.dart
> +                    });
ご指摘ありがとうございます。
おっしゃる通りなので、setStateを削除します！

2023-03-23 03:18 UTC, iu-yusei commented on lib/screens/tag_page.dart
> +            if (model.isLoading && model.tags.isEmpty) {
ご助言いただきありがとうございます。別ファイルに切り分けます。

2023-03-23 04:19 UTC, iu-yusei commented
@mcz9mm @ShuheiYoshidaJP 

ご指摘いただいた点を修正し、コミットしました！
再レビューいただけますと幸いです！


## 追加実装の内容

### ① 新たなコンポーネントの追加
#### 1.  `lib/components/loading_widget.dart`

ローディングアニメーションを表示するためのWidgetをコンポーネント化しました。

#### 2. `lib/components/tag_card.dart`

`lib/components/tag_card.dart`に記載されていたTagCardを別ファイルに切り出しました。

#### 3.  `lib/components/tag_card_text.dart`

`TagCardクラス`で共通利用するText Widgetを別ファイルに切り出しました。

<br>

### ② DRYの原則に従ってリファクタリング
対象ファイル：`lib/screens/tag_page.dart`
https://github.com/shinonome-inc/qiita_client_yusei/pull/10#discussion_r1144777952

buildメソッド内のConsumer<TagViewModel>の中身をメソッドに切り出ました。

`_buildInitialLoadingWidget()`→インターネット接続確認中のローディング

`_buildNoInternetWidget() `→インターネットに接続されていない場合のウィジェット

`_buildLoadingWidget() `→タグが読み込まれていない場合のローディング

`_buildTagsGridView(TagViewModel model)`→タグが読み込まれた場合のグリッドビュー

<br>

### ③不要なコードを削除

- `lib/view_model/tag_view_model.dart`のsetState()を削除
https://github.com/shinonome-inc/qiita_client_yusei/pull/10#discussion_r1144784988

- `lib/screens/tag_page.dart`のScrollControllerを削除
https://github.com/shinonome-inc/qiita_client_yusei/pull/10#discussion_r1144778456

- `lib/components/custom_btn.dart`で下記のような警告文が出ていたので解決

```shell
[_CustomButtonState createState() => _CustomButtonState();](info: Invalid use of a private type in a public API. (library_private_types_in_public_api at [flutter_app] lib/components/custom_btn.dart:19))
```

<br>

## プレビュー画面(iOS)

<img src="https://user-images.githubusercontent.com/78660150/227098704-3a265cc9-6363-45d7-8e43-44c61410ee8f.gif" width="320">

## プレビュー画面(Android)
<video src="https://user-images.githubusercontent.com/78660150/227101884-41404f90-bd75-4708-b188-14343a292460.webm"></video>

2023-03-23 07:55 UTC, mcz9mm approved these changes
LGTM👍

2023-03-23 10:37 UTC, ShuheiYoshidaJP commented
オッケーです。マージします。

2023-03-23 10:37 UTC, merged