7 create my page unauthenticated
shinonome-inc/qiita_client_yusei pull request #19
Opened 2023-03-27 22:03 UTC by iu-yusei

**マイページの実装**を行いました。
レビューいただけますと幸いです。

こちらは、未ログイン時の画面作成用のプルリクですが、**認証後に表示するUIは仮で作成**しました。
認証機能実装後に、再度レビュー依頼を出させていただきたいと考えています。

## ①実装内容（全体）

- [x] **未ログイン時の画面作成→完了**

- [x] **ログイン画面に戻る機能→完了**

- [x] **Feed画面とTag詳細画面のWidgetを共通化**

- [x] **不要なコードを削除**

- [x] **ログイン認証したユーザー情報をマイページに表示（仮）**

<br>

> ↓プレビュー画面（iPhone 14）
> <img src="https://user-images.githubusercontent.com/78660150/228076665-bfdfee0a-bb4b-4797-92a2-a2f6b318453c.gif" width="280px">

※最初は「ログインせずに利用する」ボタンをクリックして、Feed画面にアクセスしています。

<br>

> ↓プレビュー画面（Android）
> <video src="https://user-images.githubusercontent.com/78660150/228076474-77e8b553-c4a4-4864-acc9-66781b2e2023.webm" width="350"></video>

<br>

## ②実装内容（詳細：各ファイル）

###  `lib/api/qiita_api_service.dart`
- accessTokenの有無に応じて、送るGETリクエストの内容を切り替える処理をif文で実装しました。
- 認証済みのユーザー情報を取得するためのメソッド（`fetchUserData`）を追加しました。

### `lib/components/article_list_body.dart`
- pageNameが"my_page"のときのみ、認証済みユーザーのプロフィールを表示するUIを表示するように設定しました。

### `lib/components/my_page_profile.dart`
- 認証済みユーザーのプロフィールを表示するUIを実装しました。

### `lib/components/tag_card.dart`
- 不要なコードを削除しました。

### `lib/main.dart`
- `lib/api/qiita_api_service.dart`で定義していた変数`accessToken`をアプリ全体で共通利用できるように、こちらのファイルに移動しました。

### `lib/model/user.dart`
- ユーザー情報を取得する際に利用する`User`モデルを定義しています。

### `lib/screens/feed_page.dart`
- 記事一覧を表示する際には、`ArticleDetailListBodyContent`を利用するように設定し、不要なコードを削除しました。（Feed画面とTag詳細画面のWidgetを共通化）

### `lib/screens/my_page.dart`
- 未ログイン画面を作成しました。
- アクセストークンがあるときは、`ArticleDetailListBodyContent`経由で（認証済みユーザーのプロフィール）を表示するように設定しました。

### `lib/screens/tag_page.dart`
- 不要なコードを削除

### `lib/screens/top_page.dart`
- ２つのボタンに押した時の処理を追加

>**認証系のフローを仮実装**するために、下記のような処理を追加しました。
>「ログインする」ボタンを押した時→`accessTokenを設定`
>「ログインせずに利用する」ボタンを押した時→`accessTokenに空文字を代入`

### `lib/view_model/my_page_view_model.dart`
- ユーザーの情報をAPIから取得して、保持するためのViewModelを定義しています。

### `lib/view_model/tag_view_model.dart`
- インデントを調整しました。

### `pubspec.yaml`
- `lib/api/qiita_api_service.dart`で、認証済みのユーザー情報を取得する際に利用するパッケージ`dio`を追加しました。

<br>

2023-03-28 12:55 UTC, kota78 commented on lib/api/qiita_api_service.dart
> +          }
```
response = await http.get(
            Uri.parse(url),
            headers: (accessToken != '')
                ? {
                    'Authorization': 'Bearer $accessToken',
                  }
                : null,
          );
```
こんな感じの書き方でもいいかもですね

2023-03-28 12:55 UTC, kota78 commented on lib/components/article_list_body.dart
> +        if (pageName == "my_page") {
何のページかを取得するのにStringでもいいですが、[enum](https://kimuralog.com/?p=2378)を使うと綺麗かもしれません。
```
enum PageName{
    topPage,
    feedPage
    myPage,
 }
```
みたいな感じで。
自分だったらmodelディレクトリの中にpage_name.dartを作りその中に記載するかなと思います。
複数使うようでしたらlib/common/enum/~.dartとかでもいい気がします。

2023-03-28 12:55 UTC, kota78 commented on lib/screens/top_page.dart
> +                    accessToken = '3341b23482c9b4df03fad426ae9a153bebaacb02';
今は仮置きだと思うので大丈夫ですが、認証の際アクセストークンを保存するのに[shared_preference](https://virment.com/how-to-use-shared-preferences-in-flutter/)というパッケージを使うと便利です。変数ではなく端末のローカルにデータを保存できます。

2023-03-28 12:56 UTC, kota78 commented
とてもよくできてると思います！
動作も問題ないですので、自分だったらこうするかな、というコメントをさせていただきました。

2023-03-28 13:13 UTC, iu-yusei commented on lib/components/article_list_body.dart
> +        if (pageName == "my_page") {
アドバイスありがとうございます！
enumを利用した実装方法に興味があるので、試してみたいと思います！

2023-03-28 13:17 UTC, iu-yusei commented on lib/screens/top_page.dart
> +                    accessToken = '3341b23482c9b4df03fad426ae9a153bebaacb02';
アドバイスありがとうございます！
shared_preferenceを利用した実装を試してみます！

2023-03-28 21:59 UTC, na7ei commented
@kota78 

ご指摘いただいた点を修正し、コミットしました！
再レビューいただけますと幸いです！

## 修正内容

### ①httpリクエスト関連の処理(if文)をリファクタリング
- https://github.com/shinonome-inc/qiita_client_yusei/pull/19#discussion_r1150521505
対象ファイル： `lib/api/qiita_api_service.dart`
ご教示いただいた通りに、if文を書き換えてみました。

```dart
response = await http.get(
            Uri.parse(url),
            headers: (accessToken != '')
                ? {
                    'Authorization': 'Bearer $accessToken',
                  }
                : null,
          );

```

### ②pageNameをString型から列挙型(enum)に変換
- https://github.com/shinonome-inc/qiita_client_yusei/pull/19#discussion_r1150537692
対象ファイル： `qiita_api_service.dart`、`lib/components/article_list.dart`、`lib/components/article_list_body.dart`、`lib/model/page_name.dart`、`lib/screens/feed_page.dart`、`lib/screens/my_page.dart`、`lib/screens/tag_detail_list_page.dart`、`lib/view_model/feed_view_model.dart`
pageNameをStrig型から列挙型に変更しました。


### ③shared_preferenceパッケージを導入
- https://github.com/shinonome-inc/qiita_client_yusei/pull/19#discussion_r1150567434
対象ファイル： `top_page.dart`、`main.dart`
shared_preferenceを導入し、アクセストークンをローカルに保存しつつ、グローバル変数に代入する処理を実装しました。
※認証系実装時に、Qiita APIから取得したトークンを代入する処理に変更します。

↓Android端末（ローカル）にアクセストークンが保存されていることを確認できました。
<img width="1000"  height="300" alt="image" src="https://user-images.githubusercontent.com/78660150/228368885-0ecc8e06-d2de-4ee2-a24e-25055b002da8.png">



<hr>

## プレビュー画面(iOS)

<img width="298" src="https://user-images.githubusercontent.com/78660150/228373607-04e3b351-7bf3-4584-8565-eb81977f3541.gif">

<br>

## プレビュー画面(Android)
<video src="https://user-images.githubusercontent.com/78660150/228375316-1bf0fdb1-e218-4369-97cf-4afc1a258677.webm"></video>


<br>

2023-03-29 01:59 UTC, kota78 commented on lib/api/qiita_api_service.dart
> +      switch (pageName) {
なるほど！switchいいですね

2023-03-29 01:59 UTC, kota78 commented on lib/components/article_list.dart
> +        if (pageName == PageName.feed && pageName == PageName.myPage) {
ここって「または」ではないですか？

2023-03-29 01:59 UTC, kota78 commented on lib/screens/top_page.dart
> +    //3秒間のローディングアニメーションを追加
ここは認証実装時に、認証が完了するまでローディングとかに変える感じですかね？
3秒にしたのが何故か気になりました。

2023-03-29 09:12 UTC, iu-yusei commented on lib/components/article_list.dart
> +        if (pageName == PageName.feed && pageName == PageName.myPage) {
おっしゃる通りです！修正します！

2023-03-29 09:37 UTC, na7ei commented on lib/screens/top_page.dart
> +    //3秒間のローディングアニメーションを追加
3秒間にした意味は特にないです！
おっしゃる通りで、認証系実装時に、認証が完了する（アクセストークンが取得される）までローディングする処理に変更する予定です。

2023-03-29 09:38 UTC, iu-yusei commented on lib/api/qiita_api_service.dart
> +      switch (pageName) {
ありがとうございます！

2023-03-29 10:04 UTC, iu-yusei commented
@kota78 

ご指摘いただいた点を修正し、コミットしました！
再レビューいただけますと幸いです！

## 修正内容

### ①if文の条件式を修正
- https://github.com/shinonome-inc/qiita_client_yusei/pull/19#discussion_r1151313572
対象ファイル： ``
if文の条件式が間違っていたので、修正しました。

### ②アクセストークンが取得されている時のみ、ローディングするように修正を加えました。
- https://github.com/shinonome-inc/qiita_client_yusei/pull/19#discussion_r1151316110
対象ファイル： ``、
現在の実装方法だと、アクセストークンが一瞬で取得され、ローディングアイコンが表示されない状態になっているので、一秒間の遅延を入れました。

<hr>

## プレビュー画面(iOS)

<img width="298" src="https://user-images.githubusercontent.com/78660150/228494713-b76b73c1-cb4b-4b3a-8ef3-97f6d8538a0e.gif">

<br>

## プレビュー画面(Android)
<video src="https://user-images.githubusercontent.com/78660150/228499352-55fcd7b2-b02a-4651-b2bf-cbd6ad5eeaa3.webm"></video>


<br>

2023-03-29 10:10 UTC, kota78 commented
lgtmです。
実装にきちんと意図があり、とても良いと思います！
尊敬です。

2023-03-29 10:16 UTC, iu-yusei commented
@kota78 
ありがとうございます！
僕も大変勉強になりました！

2023-03-29 12:52 UTC, KobayashiYoh requested changes
1点だけコメントしました。

2023-03-29 12:52 UTC, KobayashiYoh commented on lib/screens/my_page.dart
> +              const Text(
figma上だとアイコンは存在しないと思われるのですが、いかがでしょうか。

2023-03-29 14:21 UTC, iu-yusei commented on lib/screens/my_page.dart
> +              const Text(
オリジナルでつけたものです。
要件にはないものなので、消しておきます！

2023-03-29 14:35 UTC, iu-yusei commented
@KobayashiYoh 

修正を加えました！
ご確認いただけますと幸いです！

## 修正内容

- [x] マイページ（未ログイン時）のアイコンを削除
- https://github.com/shinonome-inc/qiita_client_yusei/pull/19#discussion_r1151894453
不要なアイコンを削除し、高さの調節を行いました。

<hr>

## マイページのレイアウト（iOS）

<img width="298" src="https://user-images.githubusercontent.com/78660150/228572838-87d19169-3c0e-42d8-9905-19d71d0932ba.png">

<br>

2023-03-29 14:45 UTC, KobayashiYoh approved these changes

2023-03-29 14:45 UTC, KobayashiYoh commented
OKです！
マージします！

2023-03-29 14:45 UTC, merged